// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file movies.proto (package movies, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message movies.GetMovieRequest
 */
export class GetMovieRequest extends Message<GetMovieRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  constructor(data?: PartialMessage<GetMovieRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "movies.GetMovieRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMovieRequest {
    return new GetMovieRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMovieRequest {
    return new GetMovieRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMovieRequest {
    return new GetMovieRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMovieRequest | PlainMessage<GetMovieRequest> | undefined, b: GetMovieRequest | PlainMessage<GetMovieRequest> | undefined): boolean {
    return proto3.util.equals(GetMovieRequest, a, b);
  }
}

/**
 * @generated from message movies.MovieReply
 */
export class MovieReply extends Message<MovieReply> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: double score = 4;
   */
  score = 0;

  /**
   * @generated from field: bool adult = 5;
   */
  adult = false;

  /**
   * @generated from field: string posterPath = 6;
   */
  posterPath = "";

  /**
   * @generated from field: string language = 7;
   */
  language = "";

  /**
   * @generated from field: string releaseDate = 8;
   */
  releaseDate = "";

  constructor(data?: PartialMessage<MovieReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "movies.MovieReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "adult", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "posterPath", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "language", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "releaseDate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MovieReply {
    return new MovieReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MovieReply {
    return new MovieReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MovieReply {
    return new MovieReply().fromJsonString(jsonString, options);
  }

  static equals(a: MovieReply | PlainMessage<MovieReply> | undefined, b: MovieReply | PlainMessage<MovieReply> | undefined): boolean {
    return proto3.util.equals(MovieReply, a, b);
  }
}

