// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file movies.proto (package movies, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMovieRequest, MovieReply } from "./movies_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service movies.MovieGrpc
 */
export const MovieGrpc = {
  typeName: "movies.MovieGrpc",
  methods: {
    /**
     * @generated from rpc movies.MovieGrpc.GetMovieById
     */
    getMovieById: {
      name: "GetMovieById",
      I: GetMovieRequest,
      O: MovieReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

