export {default as ExampleCommonPage} from './ExampleCommonPage/ExampleCommonPage'
export {default as HomePage} from './HomePage/HomePage'
export {default as MoviesPage} from './MoviesPage/MoviesPage'
export {default as MoviePage} from './MoviePage/MoviePage'
export {default as SignInPage} from './SignInPage/SignInPage'
export {default as SignUpPage} from './SignUpPage/SignUpPage'
